[package]
name = "minerva-voucher"
version = "0.1.4"
edition = "2018"
authors = ["ANIMA Minerva toolkit"]

[lib]
name = "minerva_voucher"

[features]
default = ["validate"]
validate = ["minerva-mbedtls/v3"]
validate-lts = ["minerva-mbedtls"]
validate-lts-xtensa-kludge = ["minerva-mbedtls"]
std = []

[dependencies]
mcu-if = { git = "https://github.com/AnimaGUS-minerva/mcu-if", rev = "6543b39" }
cose = { git = "https://github.com/j-devel/cose-rust", rev = "9907d61", default-features = false }

minerva-mbedtls = { git = "https://github.com/AnimaGUS-minerva/minerva-mbedtls", rev = "0acc840", default-features = false, optional = true }
#minerva-mbedtls = { path = "../minerva-mbedtls--x86", default-features = false, optional = true }
