[package]
name = "minerva-voucher"
version = "0.2.1"
description = "Library to use BRSKI (https://datatracker.ietf.org/doc/html/rfc8995) Voucher in Rust"
edition = "2018"
authors = ["ANIMA Minerva toolkit"]

[lib]
name = "minerva_voucher"

[features]
default = ["validate"]
validate = ["minerva-mbedtls/v3"]
validate-lts = ["minerva-mbedtls"]
std = []

[dependencies]
mcu-if = { git = "https://github.com/AnimaGUS-minerva/mcu-if", rev = "6543b39" }

cose = { git = "https://github.com/j-devel/cose-rust", rev = "1d34d34", default-features = false }
#cose = { path = "../../j-devel/cose-rust", default-features = false }

minerva-mbedtls = { git = "https://github.com/AnimaGUS-minerva/minerva-mbedtls", rev = "58abf6e", default-features = false, optional = true }
#minerva-mbedtls = { path = "../minerva-mbedtls--x86", default-features = false, optional = true }
