[package]
name = "rust-mbedtls"
version = "0.1.0"
edition = "2018"
authors = ["ANIMA Minerva toolkit"]

[dependencies]
minerva-voucher = { path = "../..", default-features = false, features = ["std"] }
mbedtls = "0.8.1"
rand = "0.4"
